version: 0.2

phases:
  build:
    commands:
      - npm i && npm run build
      # Please change the s3 bucket URI
      - aws s3 cp --recursive dist/ s3://todolist-borja/
      # Please change the distribution id
      - aws cloudfront create-invalidation --distribution-id E2FJI58Q6BB619 --paths "/*"
